package config

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestLoadUsesDefaultsWhenNoEnv(t *testing.T) {
	unsetEnv(t, "PORT")
	unsetEnv(t, "LOG_LEVEL")
	unsetEnv(t, "LLM_OPENAI_BASE_URL")
	unsetEnv(t, "LLM_OPENAI_API_KEY")
	unsetEnv(t, "LLM_OPENAI_MODEL")
	unsetEnv(t, "CODING_AGENT_NAME")
	unsetEnv(t, "CODING_AGENT_PROVIDER")
	unsetEnv(t, "CODING_AGENT_MODEL")
	unsetEnv(t, "GITHUB_WEBHOOK_SECRET")
	unsetEnv(t, "GITHUB_APP_ID")
	unsetEnv(t, "GITHUB_APP_PRIVATE_KEY")
	unsetEnv(t, "GITHUB_API_BASE_URL")
	unsetEnv(t, "MAX_JOB_WORKERS")
	unsetEnv(t, "REPLYCOMMENT_TRIGGER_NAME")
	unsetEnv(t, "REVIEW")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES")
	unsetEnv(t, "REVIEW_EVENTS")
	unsetEnv(t, "OVERVIEW")
	unsetEnv(t, "OVERVIEW_EVENTS")
	unsetEnv(t, "OVERVIEW_ISSUE_ALIGNMENT")
	unsetEnv(t, "REPLYCOMMENT")
	unsetEnv(t, "REPLYCOMMENT_EVENTS")
	unsetEnv(t, "REPLYCOMMENT_ACTIONS")
	unsetEnv(t, "AUTOGEN")
	unsetEnv(t, "AUTOGEN_EVENTS")
	unsetEnv(t, "AUTOGEN_DOCS")
	unsetEnv(t, "AUTOGEN_TESTS")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	cfg, err := Load()
	require.NoError(t, err)
	require.Equal(t, "info", cfg.LogLevel)
	require.Equal(t, "", cfg.OpenAI.BaseURL)
	require.Equal(t, "", cfg.OpenAI.APIKey)
	require.Equal(t, "", cfg.OpenAI.Model)
	require.Equal(t, "opencode", cfg.CodingAgent.Agent)
	require.Equal(t, "", cfg.CodingAgent.Provider)
	require.Equal(t, "", cfg.CodingAgent.Model)
	require.Equal(t, "8080", cfg.Server.Port)
	require.Equal(t, 3, cfg.Server.MaxJobWorkers)
	require.Equal(t, "", cfg.Server.GitHub.WebhookSecret)
	require.Equal(t, "", cfg.Server.GitHub.AppID)
	require.Equal(t, "", cfg.Server.GitHub.AppPrivateKey)
	require.Equal(t, "https://api.github.com", cfg.Server.GitHub.APIBaseURL)
	require.Equal(t, "autogitbot", cfg.ReplyComment.TriggerName)
	require.True(t, cfg.Review.Enabled)
	require.False(t, cfg.Review.SuggestedChangesEnabled)
	require.Equal(t, []string{"opened", "synchronize", "reopened"}, cfg.Review.Events)
	require.True(t, cfg.Overview.Enabled)
	require.Equal(t, []string{"opened"}, cfg.Overview.Events)
	require.True(t, cfg.Overview.IssueAlignmentEnabled)
	require.False(t, cfg.Autogen.Enabled)
	require.Equal(t, []string{"opened", "reopened", "synchronize"}, cfg.Autogen.Events)
	require.False(t, cfg.Autogen.DocsEnabled)
	require.False(t, cfg.Autogen.TestsEnabled)
	require.True(t, cfg.ReplyComment.Enabled)
	require.Equal(t, []string{"issue_comment", "pull_request_review_comment"}, cfg.ReplyComment.Events)
	require.Equal(t, []string{"created"}, cfg.ReplyComment.Actions)
	require.Equal(t, "autogitbot", cfg.ReplyComment.TriggerName)
}

func TestLoadReadsDotEnvWhenEnvMissing(t *testing.T) {
	unsetEnv(t, "LLM_OPENAI_BASE_URL")
	unsetEnv(t, "LLM_OPENAI_API_KEY")
	unsetEnv(t, "LLM_OPENAI_MODEL")
	unsetEnv(t, "CODING_AGENT_NAME")
	unsetEnv(t, "CODING_AGENT_PROVIDER")
	unsetEnv(t, "CODING_AGENT_MODEL")
	unsetEnv(t, "PORT")
	unsetEnv(t, "LOG_LEVEL")
	unsetEnv(t, "GITHUB_WEBHOOK_SECRET")
	unsetEnv(t, "GITHUB_APP_ID")
	unsetEnv(t, "GITHUB_APP_PRIVATE_KEY")
	unsetEnv(t, "GITHUB_API_BASE_URL")
	unsetEnv(t, "MAX_JOB_WORKERS")
	unsetEnv(t, "REPLYCOMMENT_TRIGGER_NAME")
	unsetEnv(t, "REVIEW")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES")
	unsetEnv(t, "REVIEW_EVENTS")
	unsetEnv(t, "OVERVIEW")
	unsetEnv(t, "OVERVIEW_EVENTS")
	unsetEnv(t, "OVERVIEW_ISSUE_ALIGNMENT")
	unsetEnv(t, "REPLYCOMMENT")
	unsetEnv(t, "REPLYCOMMENT_EVENTS")
	unsetEnv(t, "REPLYCOMMENT_ACTIONS")
	unsetEnv(t, "AUTOGEN")
	unsetEnv(t, "AUTOGEN_EVENTS")
	unsetEnv(t, "AUTOGEN_DOCS")
	unsetEnv(t, "AUTOGEN_TESTS")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	envPath := filepath.Join(tmp, ".env")
	require.NoError(t, os.WriteFile(envPath, []byte("LLM_OPENAI_BASE_URL=openai\nLLM_OPENAI_MODEL=gpt-4.1\nLLM_OPENAI_API_KEY=env-key\nCODING_AGENT_NAME=opencode\nCODING_AGENT_PROVIDER=codingagent\nCODING_AGENT_MODEL=model-x\nPORT=9090\nLOG_LEVEL=warning\nGITHUB_WEBHOOK_SECRET=whsec\nGITHUB_APP_ID=12345\nGITHUB_APP_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\\nabc\\n-----END PRIVATE KEY-----\nGITHUB_API_BASE_URL=https://github.example.com/api/v3\nMAX_JOB_WORKERS=9\nREPLYCOMMENT_TRIGGER_NAME=autogit\nREVIEW=true\nREVIEW_SUGGESTED_CHANGES=true\nREVIEW_EVENTS=opened,reopened\nOVERVIEW=false\nOVERVIEW_EVENTS=opened\nOVERVIEW_ISSUE_ALIGNMENT=false\nREPLYCOMMENT=false\nREPLYCOMMENT_EVENTS=issue_comment\nREPLYCOMMENT_ACTIONS=created,edited\nAUTOGEN=true\nAUTOGEN_EVENTS=opened\nAUTOGEN_DOCS=true\nAUTOGEN_TESTS=false\n"), 0o644))

	cfg, err := Load()
	require.NoError(t, err)
	require.Equal(t, "openai", cfg.OpenAI.BaseURL)
	require.Equal(t, "gpt-4.1", cfg.OpenAI.Model)
	require.Equal(t, "env-key", cfg.OpenAI.APIKey)
	require.Equal(t, "opencode", cfg.CodingAgent.Agent)
	require.Equal(t, "codingagent", cfg.CodingAgent.Provider)
	require.Equal(t, "model-x", cfg.CodingAgent.Model)
	require.Equal(t, "warning", cfg.LogLevel)
	require.Equal(t, "9090", cfg.Server.Port)
	require.Equal(t, 9, cfg.Server.MaxJobWorkers)
	require.Equal(t, "whsec", cfg.Server.GitHub.WebhookSecret)
	require.Equal(t, "12345", cfg.Server.GitHub.AppID)
	require.Equal(t, "-----BEGIN PRIVATE KEY-----\\nabc\\n-----END PRIVATE KEY-----", cfg.Server.GitHub.AppPrivateKey)
	require.Equal(t, "https://github.example.com/api/v3", cfg.Server.GitHub.APIBaseURL)
	require.Equal(t, "autogit", cfg.ReplyComment.TriggerName)
	require.True(t, cfg.Review.Enabled)
	require.True(t, cfg.Review.SuggestedChangesEnabled)
	require.Equal(t, []string{"opened", "reopened"}, cfg.Review.Events)
	require.False(t, cfg.Overview.Enabled)
	require.Equal(t, []string{"opened"}, cfg.Overview.Events)
	require.False(t, cfg.Overview.IssueAlignmentEnabled)
	require.True(t, cfg.Autogen.Enabled)
	require.Equal(t, []string{"opened"}, cfg.Autogen.Events)
	require.True(t, cfg.Autogen.DocsEnabled)
	require.False(t, cfg.Autogen.TestsEnabled)
	require.False(t, cfg.ReplyComment.Enabled)
	require.Equal(t, []string{"issue_comment"}, cfg.ReplyComment.Events)
	require.Equal(t, []string{"created", "edited"}, cfg.ReplyComment.Actions)
}

func TestLoadDoesNotOverrideExistingEnvWithDotEnv(t *testing.T) {
	t.Setenv("LLM_OPENAI_BASE_URL", "gemini")
	t.Setenv("LLM_OPENAI_MODEL", "from-env")
	t.Setenv("LLM_OPENAI_API_KEY", "env-key")
	t.Setenv("CODING_AGENT_NAME", "opencode")
	t.Setenv("CODING_AGENT_PROVIDER", "codingagent")
	t.Setenv("CODING_AGENT_MODEL", "model-y")
	t.Setenv("PORT", "7777")
	t.Setenv("LOG_LEVEL", "error")
	t.Setenv("GITHUB_WEBHOOK_SECRET", "set-secret")
	t.Setenv("GITHUB_APP_ID", "set-app-id")
	t.Setenv("GITHUB_APP_PRIVATE_KEY", "set-private-key")
	t.Setenv("GITHUB_API_BASE_URL", "https://set.example.com")
	t.Setenv("MAX_JOB_WORKERS", "5")
	t.Setenv("REPLYCOMMENT_TRIGGER_NAME", "set-trigger")
	t.Setenv("REVIEW", "false")
	t.Setenv("REVIEW_SUGGESTED_CHANGES", "true")
	t.Setenv("REVIEW_EVENTS", "opened")
	t.Setenv("OVERVIEW", "true")
	t.Setenv("OVERVIEW_EVENTS", "opened")
	t.Setenv("OVERVIEW_ISSUE_ALIGNMENT", "false")
	t.Setenv("REPLYCOMMENT", "false")
	t.Setenv("REPLYCOMMENT_EVENTS", "issue_comment")
	t.Setenv("REPLYCOMMENT_ACTIONS", "created")
	t.Setenv("AUTOGEN", "true")
	t.Setenv("AUTOGEN_EVENTS", "opened")
	t.Setenv("AUTOGEN_DOCS", "true")
	t.Setenv("AUTOGEN_TESTS", "false")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	envPath := filepath.Join(tmp, ".env")
	require.NoError(t, os.WriteFile(envPath, []byte("LLM_OPENAI_BASE_URL=openai\nLLM_OPENAI_MODEL=from-dotenv\nLLM_OPENAI_API_KEY=dotenv-key\nCODING_AGENT_NAME=opencode\nCODING_AGENT_PROVIDER=dotenv-provider\nCODING_AGENT_MODEL=dotenv-model\nPORT=9090\nLOG_LEVEL=warning\nGITHUB_WEBHOOK_SECRET=dotenv-secret\nGITHUB_APP_ID=dotenv-app-id\nGITHUB_APP_PRIVATE_KEY=dotenv-private-key\nGITHUB_API_BASE_URL=https://dotenv.example.com\nMAX_JOB_WORKERS=11\nREPLYCOMMENT_TRIGGER_NAME=dotenv-trigger\nREVIEW=true\nREVIEW_SUGGESTED_CHANGES=false\nREVIEW_EVENTS=opened,reopened\nOVERVIEW=false\nOVERVIEW_EVENTS=opened\nOVERVIEW_ISSUE_ALIGNMENT=true\nREPLYCOMMENT=true\nREPLYCOMMENT_EVENTS=issue_comment\nREPLYCOMMENT_ACTIONS=created\nAUTOGEN=false\nAUTOGEN_EVENTS=opened\nAUTOGEN_DOCS=false\nAUTOGEN_TESTS=true\n"), 0o644))

	cfg, err := Load()
	require.NoError(t, err)
	require.Equal(t, "gemini", cfg.OpenAI.BaseURL)
	require.Equal(t, "from-env", cfg.OpenAI.Model)
	require.Equal(t, "env-key", cfg.OpenAI.APIKey)
	require.Equal(t, "opencode", cfg.CodingAgent.Agent)
	require.Equal(t, "codingagent", cfg.CodingAgent.Provider)
	require.Equal(t, "model-y", cfg.CodingAgent.Model)
	require.Equal(t, "error", cfg.LogLevel)
	require.Equal(t, "7777", cfg.Server.Port)
	require.Equal(t, 5, cfg.Server.MaxJobWorkers)
	require.Equal(t, "set-secret", cfg.Server.GitHub.WebhookSecret)
	require.Equal(t, "set-app-id", cfg.Server.GitHub.AppID)
	require.Equal(t, "set-private-key", cfg.Server.GitHub.AppPrivateKey)
	require.Equal(t, "https://set.example.com", cfg.Server.GitHub.APIBaseURL)
	require.Equal(t, "set-trigger", cfg.ReplyComment.TriggerName)
	require.False(t, cfg.Review.Enabled)
	require.True(t, cfg.Review.SuggestedChangesEnabled)
	require.Equal(t, []string{"opened"}, cfg.Review.Events)
	require.True(t, cfg.Overview.Enabled)
	require.Equal(t, []string{"opened"}, cfg.Overview.Events)
	require.False(t, cfg.Overview.IssueAlignmentEnabled)
	require.False(t, cfg.ReplyComment.Enabled)
	require.Equal(t, []string{"issue_comment"}, cfg.ReplyComment.Events)
	require.Equal(t, []string{"created"}, cfg.ReplyComment.Actions)
	require.True(t, cfg.Autogen.Enabled)
	require.Equal(t, []string{"opened"}, cfg.Autogen.Events)
	require.True(t, cfg.Autogen.DocsEnabled)
	require.False(t, cfg.Autogen.TestsEnabled)
}

func TestLoadReturnsErrorForInvalidDotEnv(t *testing.T) {
	unsetEnv(t, "LLM_OPENAI_BASE_URL")
	unsetEnv(t, "LLM_OPENAI_API_KEY")
	unsetEnv(t, "LLM_OPENAI_MODEL")
	unsetEnv(t, "CODING_AGENT_NAME")
	unsetEnv(t, "CODING_AGENT_PROVIDER")
	unsetEnv(t, "CODING_AGENT_MODEL")
	unsetEnv(t, "PORT")
	unsetEnv(t, "LOG_LEVEL")
	unsetEnv(t, "GITHUB_WEBHOOK_SECRET")
	unsetEnv(t, "GITHUB_APP_ID")
	unsetEnv(t, "GITHUB_APP_PRIVATE_KEY")
	unsetEnv(t, "GITHUB_API_BASE_URL")
	unsetEnv(t, "MAX_JOB_WORKERS")
	unsetEnv(t, "REPLYCOMMENT_TRIGGER_NAME")
	unsetEnv(t, "REVIEW")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES")
	unsetEnv(t, "REVIEW_EVENTS")
	unsetEnv(t, "OVERVIEW")
	unsetEnv(t, "OVERVIEW_EVENTS")
	unsetEnv(t, "OVERVIEW_ISSUE_ALIGNMENT")
	unsetEnv(t, "REPLYCOMMENT")
	unsetEnv(t, "REPLYCOMMENT_EVENTS")
	unsetEnv(t, "REPLYCOMMENT_ACTIONS")
	unsetEnv(t, "AUTOGEN")
	unsetEnv(t, "AUTOGEN_EVENTS")
	unsetEnv(t, "AUTOGEN_DOCS")
	unsetEnv(t, "AUTOGEN_TESTS")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	envPath := filepath.Join(tmp, ".env")
	require.NoError(t, os.WriteFile(envPath, []byte("CODING_AGENT_NAME=\"unterminated\n"), 0o644))

	_, err = Load()
	require.Error(t, err)
}

func TestLoadParsesOverviewEnabledFalse(t *testing.T) {
	unsetEnv(t, "LLM_OPENAI_BASE_URL")
	unsetEnv(t, "LLM_OPENAI_API_KEY")
	unsetEnv(t, "LLM_OPENAI_MODEL")
	unsetEnv(t, "CODING_AGENT_NAME")
	unsetEnv(t, "CODING_AGENT_PROVIDER")
	unsetEnv(t, "CODING_AGENT_MODEL")
	unsetEnv(t, "PORT")
	unsetEnv(t, "LOG_LEVEL")
	unsetEnv(t, "GITHUB_WEBHOOK_SECRET")
	unsetEnv(t, "GITHUB_APP_ID")
	unsetEnv(t, "GITHUB_APP_PRIVATE_KEY")
	unsetEnv(t, "GITHUB_API_BASE_URL")
	unsetEnv(t, "MAX_JOB_WORKERS")
	unsetEnv(t, "REPLYCOMMENT_TRIGGER_NAME")
	unsetEnv(t, "REVIEW")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES")
	unsetEnv(t, "REVIEW_EVENTS")
	unsetEnv(t, "OVERVIEW_EVENTS")
	unsetEnv(t, "OVERVIEW_ISSUE_ALIGNMENT")
	unsetEnv(t, "REPLYCOMMENT")
	unsetEnv(t, "REPLYCOMMENT_EVENTS")
	unsetEnv(t, "REPLYCOMMENT_ACTIONS")
	unsetEnv(t, "AUTOGEN")
	unsetEnv(t, "AUTOGEN_EVENTS")
	unsetEnv(t, "AUTOGEN_DOCS")
	unsetEnv(t, "AUTOGEN_TESTS")
	t.Setenv("OVERVIEW", "false")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	cfg, err := Load()
	require.NoError(t, err)
	require.False(t, cfg.Overview.Enabled)
}

func TestLoadFallsBackForInvalidOverviewEnabled(t *testing.T) {
	unsetEnv(t, "LLM_OPENAI_BASE_URL")
	unsetEnv(t, "LLM_OPENAI_API_KEY")
	unsetEnv(t, "LLM_OPENAI_MODEL")
	unsetEnv(t, "CODING_AGENT_NAME")
	unsetEnv(t, "CODING_AGENT_PROVIDER")
	unsetEnv(t, "CODING_AGENT_MODEL")
	unsetEnv(t, "PORT")
	unsetEnv(t, "LOG_LEVEL")
	unsetEnv(t, "GITHUB_WEBHOOK_SECRET")
	unsetEnv(t, "GITHUB_APP_ID")
	unsetEnv(t, "GITHUB_APP_PRIVATE_KEY")
	unsetEnv(t, "GITHUB_API_BASE_URL")
	unsetEnv(t, "MAX_JOB_WORKERS")
	unsetEnv(t, "REVIEW")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES")
	unsetEnv(t, "REVIEW_EVENTS")
	unsetEnv(t, "OVERVIEW_EVENTS")
	unsetEnv(t, "OVERVIEW_ISSUE_ALIGNMENT")
	unsetEnv(t, "REPLYCOMMENT")
	unsetEnv(t, "REPLYCOMMENT_EVENTS")
	unsetEnv(t, "REPLYCOMMENT_ACTIONS")
	unsetEnv(t, "AUTOGEN")
	unsetEnv(t, "AUTOGEN_EVENTS")
	unsetEnv(t, "AUTOGEN_DOCS")
	unsetEnv(t, "AUTOGEN_TESTS")
	t.Setenv("OVERVIEW", "not-a-bool")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	cfg, err := Load()
	require.NoError(t, err)
	require.True(t, cfg.Overview.Enabled)
}

func unsetEnv(t *testing.T, key string) {
	t.Helper()
	oldValue, hadValue := os.LookupEnv(key)
	require.NoError(t, os.Unsetenv(key))
	t.Cleanup(func() {
		if hadValue {
			_ = os.Setenv(key, oldValue)
			return
		}
		_ = os.Unsetenv(key)
	})
}
