package config

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestLoadUsesDefaultsWhenNoEnv(t *testing.T) {
	unsetEnv(t, "PORT")
	unsetEnv(t, "LOG_LEVEL")
	unsetEnv(t, "OVERVIEW_ENABLED")
	unsetEnv(t, "OPENAI_BASE_URL")
	unsetEnv(t, "OPENAI_API_KEY")
	unsetEnv(t, "OPENAI_MODEL")
	unsetEnv(t, "CODING_AGENT_NAME")
	unsetEnv(t, "CODING_AGENT_PROVIDER")
	unsetEnv(t, "CODING_AGENT_MODEL")
	unsetEnv(t, "GITHUB_WEBHOOK_SECRET")
	unsetEnv(t, "GITHUB_APP_ID")
	unsetEnv(t, "GITHUB_APP_PRIVATE_KEY")
	unsetEnv(t, "GITHUB_API_BASE_URL")
	unsetEnv(t, "REPLYCOMMENT_TRIGGER_NAME")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_ENABLED")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MIN_SEVERITY")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_CANDIDATES")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_GROUP_SIZE")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_WORKERS")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_GROUP_TIMEOUT_MS")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_GENERATE_TIMEOUT_MS")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	cfg, err := Load()
	require.NoError(t, err)
	require.Equal(t, "info", cfg.LogLevel)
	require.Nil(t, cfg.OverviewEnabled)
	require.Equal(t, "gemini", cfg.OpenAI.BaseURL)
	require.Equal(t, "gemini-2.5-flash-lite", cfg.OpenAI.Model)
	require.Equal(t, "opencode", cfg.CodingAgent.Agent)
	require.Equal(t, "openai", cfg.CodingAgent.Provider)
	require.Equal(t, "gemini-2.5-flash-lite", cfg.CodingAgent.Model)
	require.Equal(t, "8080", cfg.Server.Port)
	require.Equal(t, "", cfg.Server.GitHub.WebhookSecret)
	require.Equal(t, "", cfg.Server.GitHub.AppID)
	require.Equal(t, "", cfg.Server.GitHub.AppPrivateKey)
	require.Equal(t, "https://api.github.com", cfg.Server.GitHub.APIBaseURL)
	require.Equal(t, "autogitbot", cfg.Server.GitHub.ReplyCommentTriggerName)
	require.False(t, cfg.SuggestedChanges.Enabled)
	require.Equal(t, "MAJOR", cfg.SuggestedChanges.MinSeverity)
	require.Equal(t, 50, cfg.SuggestedChanges.MaxCandidates)
	require.Equal(t, 5, cfg.SuggestedChanges.MaxGroupSize)
	require.Equal(t, 3, cfg.SuggestedChanges.MaxWorkers)
	require.Equal(t, 20000, cfg.SuggestedChanges.GroupTimeoutMS)
	require.Equal(t, 30000, cfg.SuggestedChanges.GenerateTimeoutMS)
}

func TestLoadReadsDotEnvWhenEnvMissing(t *testing.T) {
	unsetEnv(t, "OPENAI_BASE_URL")
	unsetEnv(t, "OPENAI_MODEL")
	unsetEnv(t, "OPENAI_API_KEY")
	unsetEnv(t, "CODING_AGENT_NAME")
	unsetEnv(t, "CODING_AGENT_PROVIDER")
	unsetEnv(t, "CODING_AGENT_MODEL")
	unsetEnv(t, "PORT")
	unsetEnv(t, "LOG_LEVEL")
	unsetEnv(t, "OVERVIEW_ENABLED")
	unsetEnv(t, "GITHUB_WEBHOOK_SECRET")
	unsetEnv(t, "GITHUB_APP_ID")
	unsetEnv(t, "GITHUB_APP_PRIVATE_KEY")
	unsetEnv(t, "GITHUB_API_BASE_URL")
	unsetEnv(t, "REPLYCOMMENT_TRIGGER_NAME")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_ENABLED")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MIN_SEVERITY")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_CANDIDATES")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_GROUP_SIZE")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_WORKERS")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_GROUP_TIMEOUT_MS")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_GENERATE_TIMEOUT_MS")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	envPath := filepath.Join(tmp, ".env")
	require.NoError(t, os.WriteFile(envPath, []byte("OPENAI_BASE_URL=openai\nOPENAI_MODEL=my-model\nOPENAI_API_KEY=env-key\nPORT=9090\nLOG_LEVEL=warning\nGITHUB_WEBHOOK_SECRET=whsec\nGITHUB_APP_ID=12345\nGITHUB_APP_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\\nabc\\n-----END PRIVATE KEY-----\nGITHUB_API_BASE_URL=https://github.example.com/api/v3\nREPLYCOMMENT_TRIGGER_NAME=autogit\n"), 0o644))

	cfg, err := Load()
	require.NoError(t, err)
	require.Equal(t, "openai", cfg.OpenAI.BaseURL)
	require.Equal(t, "my-model", cfg.OpenAI.Model)
	require.Equal(t, "env-key", cfg.OpenAI.APIKey)
	require.Equal(t, "opencode", cfg.CodingAgent.Agent)
	require.Equal(t, "openai", cfg.CodingAgent.Provider)
	require.Equal(t, "my-model", cfg.CodingAgent.Model)
	require.Equal(t, "warning", cfg.LogLevel)
	require.Nil(t, cfg.OverviewEnabled)
	require.Equal(t, "9090", cfg.Server.Port)
	require.Equal(t, "whsec", cfg.Server.GitHub.WebhookSecret)
	require.Equal(t, "12345", cfg.Server.GitHub.AppID)
	require.Equal(t, "-----BEGIN PRIVATE KEY-----\\nabc\\n-----END PRIVATE KEY-----", cfg.Server.GitHub.AppPrivateKey)
	require.Equal(t, "https://github.example.com/api/v3", cfg.Server.GitHub.APIBaseURL)
	require.Equal(t, "autogit", cfg.Server.GitHub.ReplyCommentTriggerName)
}

func TestLoadDoesNotOverrideExistingEnvWithDotEnv(t *testing.T) {
	t.Setenv("OPENAI_BASE_URL", "gemini")
	t.Setenv("OPENAI_MODEL", "from-env")
	t.Setenv("OPENAI_API_KEY", "env-key")
	t.Setenv("CODING_AGENT_NAME", "opencode")
	t.Setenv("CODING_AGENT_PROVIDER", "anthropic")
	t.Setenv("CODING_AGENT_MODEL", "claude-3-5-haiku-latest")
	t.Setenv("PORT", "7777")
	t.Setenv("LOG_LEVEL", "error")
	t.Setenv("OVERVIEW_ENABLED", "true")
	t.Setenv("GITHUB_WEBHOOK_SECRET", "set-secret")
	t.Setenv("GITHUB_APP_ID", "set-app-id")
	t.Setenv("GITHUB_APP_PRIVATE_KEY", "set-private-key")
	t.Setenv("GITHUB_API_BASE_URL", "https://set.example.com")
	t.Setenv("REPLYCOMMENT_TRIGGER_NAME", "set-trigger")
	t.Setenv("REVIEW_SUGGESTED_CHANGES_ENABLED", "true")
	t.Setenv("REVIEW_SUGGESTED_CHANGES_MIN_SEVERITY", "CRITICAL")
	t.Setenv("REVIEW_SUGGESTED_CHANGES_MAX_CANDIDATES", "20")
	t.Setenv("REVIEW_SUGGESTED_CHANGES_MAX_GROUP_SIZE", "4")
	t.Setenv("REVIEW_SUGGESTED_CHANGES_MAX_WORKERS", "2")
	t.Setenv("REVIEW_SUGGESTED_CHANGES_GROUP_TIMEOUT_MS", "5000")
	t.Setenv("REVIEW_SUGGESTED_CHANGES_GENERATE_TIMEOUT_MS", "7000")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	envPath := filepath.Join(tmp, ".env")
	require.NoError(t, os.WriteFile(envPath, []byte("OPENAI_BASE_URL=openai\nOPENAI_MODEL=from-dotenv\nOPENAI_API_KEY=dotenv-key\nPORT=9090\nLOG_LEVEL=warning\nGITHUB_WEBHOOK_SECRET=dotenv-secret\nGITHUB_APP_ID=dotenv-app-id\nGITHUB_APP_PRIVATE_KEY=dotenv-private-key\nGITHUB_API_BASE_URL=https://dotenv.example.com\nREPLYCOMMENT_TRIGGER_NAME=dotenv-trigger\n"), 0o644))

	cfg, err := Load()
	require.NoError(t, err)
	require.Equal(t, "gemini", cfg.OpenAI.BaseURL)
	require.Equal(t, "from-env", cfg.OpenAI.Model)
	require.Equal(t, "env-key", cfg.OpenAI.APIKey)
	require.Equal(t, "opencode", cfg.CodingAgent.Agent)
	require.Equal(t, "anthropic", cfg.CodingAgent.Provider)
	require.Equal(t, "claude-3-5-haiku-latest", cfg.CodingAgent.Model)
	require.Equal(t, "error", cfg.LogLevel)
	require.NotNil(t, cfg.OverviewEnabled)
	require.True(t, *cfg.OverviewEnabled)
	require.Equal(t, "7777", cfg.Server.Port)
	require.Equal(t, "set-secret", cfg.Server.GitHub.WebhookSecret)
	require.Equal(t, "set-app-id", cfg.Server.GitHub.AppID)
	require.Equal(t, "set-private-key", cfg.Server.GitHub.AppPrivateKey)
	require.Equal(t, "https://set.example.com", cfg.Server.GitHub.APIBaseURL)
	require.Equal(t, "set-trigger", cfg.Server.GitHub.ReplyCommentTriggerName)
	require.True(t, cfg.SuggestedChanges.Enabled)
	require.Equal(t, "CRITICAL", cfg.SuggestedChanges.MinSeverity)
	require.Equal(t, 20, cfg.SuggestedChanges.MaxCandidates)
	require.Equal(t, 4, cfg.SuggestedChanges.MaxGroupSize)
	require.Equal(t, 2, cfg.SuggestedChanges.MaxWorkers)
	require.Equal(t, 5000, cfg.SuggestedChanges.GroupTimeoutMS)
	require.Equal(t, 7000, cfg.SuggestedChanges.GenerateTimeoutMS)
}

func TestLoadReturnsErrorForInvalidDotEnv(t *testing.T) {
	unsetEnv(t, "OPENAI_BASE_URL")
	unsetEnv(t, "OPENAI_MODEL")
	unsetEnv(t, "OPENAI_API_KEY")
	unsetEnv(t, "CODING_AGENT_NAME")
	unsetEnv(t, "CODING_AGENT_PROVIDER")
	unsetEnv(t, "CODING_AGENT_MODEL")
	unsetEnv(t, "PORT")
	unsetEnv(t, "LOG_LEVEL")
	unsetEnv(t, "OVERVIEW_ENABLED")
	unsetEnv(t, "GITHUB_WEBHOOK_SECRET")
	unsetEnv(t, "GITHUB_APP_ID")
	unsetEnv(t, "GITHUB_APP_PRIVATE_KEY")
	unsetEnv(t, "GITHUB_API_BASE_URL")
	unsetEnv(t, "REPLYCOMMENT_TRIGGER_NAME")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_ENABLED")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MIN_SEVERITY")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_CANDIDATES")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_GROUP_SIZE")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_WORKERS")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_GROUP_TIMEOUT_MS")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_GENERATE_TIMEOUT_MS")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	envPath := filepath.Join(tmp, ".env")
	require.NoError(t, os.WriteFile(envPath, []byte("OPENAI_BASE_URL=\"unterminated\n"), 0o644))

	_, err = Load()
	require.Error(t, err)
}

func TestLoadParsesOverviewEnabledFalse(t *testing.T) {
	unsetEnv(t, "OPENAI_BASE_URL")
	unsetEnv(t, "OPENAI_MODEL")
	unsetEnv(t, "OPENAI_API_KEY")
	unsetEnv(t, "CODING_AGENT_NAME")
	unsetEnv(t, "CODING_AGENT_PROVIDER")
	unsetEnv(t, "CODING_AGENT_MODEL")
	unsetEnv(t, "PORT")
	unsetEnv(t, "LOG_LEVEL")
	unsetEnv(t, "GITHUB_WEBHOOK_SECRET")
	unsetEnv(t, "GITHUB_APP_ID")
	unsetEnv(t, "GITHUB_APP_PRIVATE_KEY")
	unsetEnv(t, "GITHUB_API_BASE_URL")
	unsetEnv(t, "REPLYCOMMENT_TRIGGER_NAME")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_ENABLED")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MIN_SEVERITY")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_CANDIDATES")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_GROUP_SIZE")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_WORKERS")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_GROUP_TIMEOUT_MS")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_GENERATE_TIMEOUT_MS")
	t.Setenv("OVERVIEW_ENABLED", "false")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	cfg, err := Load()
	require.NoError(t, err)
	require.NotNil(t, cfg.OverviewEnabled)
	require.False(t, *cfg.OverviewEnabled)
}

func TestLoadReturnsErrorForInvalidOverviewEnabled(t *testing.T) {
	unsetEnv(t, "OPENAI_BASE_URL")
	unsetEnv(t, "OPENAI_MODEL")
	unsetEnv(t, "OPENAI_API_KEY")
	unsetEnv(t, "CODING_AGENT_NAME")
	unsetEnv(t, "CODING_AGENT_PROVIDER")
	unsetEnv(t, "CODING_AGENT_MODEL")
	unsetEnv(t, "PORT")
	unsetEnv(t, "LOG_LEVEL")
	unsetEnv(t, "GITHUB_WEBHOOK_SECRET")
	unsetEnv(t, "GITHUB_APP_ID")
	unsetEnv(t, "GITHUB_APP_PRIVATE_KEY")
	unsetEnv(t, "GITHUB_API_BASE_URL")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_ENABLED")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MIN_SEVERITY")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_CANDIDATES")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_GROUP_SIZE")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_MAX_WORKERS")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_GROUP_TIMEOUT_MS")
	unsetEnv(t, "REVIEW_SUGGESTED_CHANGES_GENERATE_TIMEOUT_MS")
	t.Setenv("OVERVIEW_ENABLED", "not-a-bool")

	tmp := t.TempDir()
	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	_, err = Load()
	require.Error(t, err)
	require.ErrorContains(t, err, "invalid OVERVIEW_ENABLED")
}

func unsetEnv(t *testing.T, key string) {
	t.Helper()
	oldValue, hadValue := os.LookupEnv(key)
	require.NoError(t, os.Unsetenv(key))
	t.Cleanup(func() {
		if hadValue {
			_ = os.Setenv(key, oldValue)
			return
		}
		_ = os.Unsetenv(key)
	})
}
